### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/var/nfs'

### ISSUE THREAD

**Issue by juroVee** [airflow-helm/charts#110]
**What is the bug?**

We have been using version 7.14.3 of this chart for some time and we have persisted our logs in shared NFS volume. This stopped working from version 8.0.0 (also 8.0.1 and 8.0.2). We are getting permission denied errors. I Tried changing chmods, recreating directories from inside of webserver/scheduler/worker pod, etc. Nothing seems to be solving this issue. Have you any ideas how to resolve this? Thanks.

Chart installation fails immediately on check-db initContainer:

```console
kubectl logs releasename-upgrade-db-abcdef -c check-db
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/nfs/logs/scheduler/2021-03-28'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/nfs/logs/scheduler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/var/nfs/logs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/local/lib/python3.8/logging/config.py", line 744, in configure_handler
    result = factory(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_processor_handler.py", line 46, in __init__
    Path(self._get_log_directory()).mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1291, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1287, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/var/nfs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 5, in <module>
    from airflow.__main__ import main
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__init__.py", line 46, in <module>
    settings.initialize()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py", line 434, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/logging_config.py", line 62, in configure_logging
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/logging_config.py", line 57, in configure_logging
    dictConfig(logging_config)
  File "/usr/local/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'processor'`
```

Note: With default logs path:

```console
logs:
  path: /opt/airflow/logs
```
everything works just fine and we are able to access mounted volume from the pod(s).

**What are your Helm values?**

```console
airflow:
  extraVolumes:
    - name: nfs-volume
      nfs:
        server: xxx.xxx.xx
        path: /some/airflow-dev
  extraVolumeMounts:
    - name: nfs-volume
      mountPath: /var/nfs

logs:
  path: /var/nfs/logs
```

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:23:52Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6+vmware.1", GitCommit:"afe4eda368a924376517be0c262541f358673efa", GitTreeState:"clean", BuildDate:"2020-12-22T01:08:16Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
```

**Comment by juroVee** [comment]
Well finally and surprisingly I managed to solve this issue by mounting NFS volume in another location inside of pod. 

Instead of:
```console
airflow:
  extraVolumes:
    - name: nfs-volume
      nfs:
        server: xxx.xxx.xx
        path: /some/airflow-dev
  extraVolumeMounts:
    - name: nfs-volume
      mountPath: /var/nfs

logs:
  path: /var/nfs/logs
```
I did it this way:
```console
airflow:
  extraVolumes:
    - name: nfs-volume
      nfs:
        server: xxx.xxx.xx
        path: /some/airflow-dev
  extraVolumeMounts:
    - name: nfs-volume
      mountPath: /opt/airflow/shared

logs:
  path: /opt/airflow/shared/logs
```
