### ISSUE TITLE
[AWS/EKS] Scheduler Failing To Start for CeleryKubernetesExecutor: "airflow.exceptions.AirflowException: Could not get scheduler_job_id"

### ISSUE THREAD

**Issue by jpmaglutac** [airflow-helm/charts#114]
**What is the bug?**

Trying out a quick cluster of the Airflow 2.0 on AWS EKS, and I've noticed that using CeleryKubernetesExecutor causes the scheduler to fail to start. Other executors are working just fine and I haven't changed any of the values other than the executor, so I'm wondering if this is a bug or if there's something further that I have to customize not indicated. Output as follows:
```console
jmaglutac@j-maglutac02:~/projects/airflow-helm$ helm install airflow-kube airflow-stable/airflow --namespace airflow-kube --set airflow.executor=CeleryKubernetesExecutor
NAME: airflow-kube
LAST DEPLOYED: Tue Mar 30 10:56:03 2021
NAMESPACE: airflow-kube
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
================
Congratulations, you have just deployed Apache Airflow!

----------------
Access the Webserver Service with your browser
----------------
  export POD_NAME=$(kubectl get pods --namespace airflow-kube -l "component=web,app=airflow" -o jsonpath="{.items[0].metadata.name}")
  echo "URL: http://127.0.0.1:8080"
  kubectl port-forward --namespace airflow-kube $POD_NAME 8080:8080
================
jmaglutac@j-maglutac02:~/projects/airflow-helm$ kubectl get po -n airflow-kube
NAME                                      READY   STATUS             RESTARTS   AGE
airflow-kube-flower-5849c756ff-2wb8r      1/1     Running            0          2m
airflow-kube-postgresql-0                 1/1     Running            0          2m
airflow-kube-redis-master-0               1/1     Running            0          2m
airflow-kube-scheduler-5d94dfc7bf-ndbpl   0/1     CrashLoopBackOff   2          2m
airflow-kube-web-7fb77f4666-xzr5z         1/1     Running            0          2m
airflow-kube-worker-0                     1/1     Running            0          2m
jmaglutac@j-maglutac02:~/projects/airflow-helm$ kubectl logs airflow-kube-scheduler-5d94dfc7bf-ndbpl -n airflow-kube
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-03-30 02:58:24,757] {scheduler_job.py:1247} INFO - Starting the scheduler
[2021-03-30 02:58:24,758] {scheduler_job.py:1252} INFO - Processing each file at most -1 times
[2021-03-30 02:58:24,759] {kubernetes_executor.py:473} INFO - Start Kubernetes executor
[2021-03-30 02:58:24,759] {scheduler_job.py:1298} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/jobs/scheduler_job.py", line 1272, in _execute
    self.executor.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/celery_kubernetes_executor.py", line 60, in start
    self.kubernetes_executor.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/executors/kubernetes_executor.py", line 475, in start
    raise AirflowException("Could not get scheduler_job_id")
airflow.exceptions.AirflowException: Could not get scheduler_job_id
[2021-03-30 02:58:24,760] {dag_processing.py:451} WARNING - Ending without manager process.
[2021-03-30 02:58:24,760] {scheduler_job.py:1301} INFO - Exited execute loop
```

**What are your Helm values?**

`airflow.executor=CeleryKubernetesExecutor`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-eks-7684af", GitCommit:"7684af4ac41370dd109ac13817023cb8063e3d45", GitTreeState:"clean", BuildDate:"2020-10-20T22:57:40Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

**Comment by dominique-vassard** [comment]
I've got the same problem with the KubernetesExecutor.
I can trigger DAGs though but when I try to run just run a task or test a dag, it fails with `airflow.exceptions.AirflowException: Could not get scheduler_job_id`

**Comment by thesuperzapper** [comment]
I believe this is related to https://github.com/apache/airflow/issues/13805

The `CeleryKubernetesExecutor` is broken in airflow `2.0.1`, I guess we will have to wait for `2.0.2`

**Comment by jdotjdot** [comment]
Same issue here, FWIW
