### ISSUE TITLE
Web service pod is never ready when scheduler replicas is greater than 1

### ISSUE THREAD

**Issue by ahayasic** [airflow-helm/charts#189]
### What is the bug?
When running `scheduler.replicas: 1`, deployments work well.
But when `scheduler.replicas` is set to more than 1, the web service pod cannot handle connections to port 8080.
Same behavior occurs when `web.replicas` is also more than 1 (so, it may be related to #72).

(I'm running the Chart on Minikube)

#### Pod Description
```console
Name:         airflow-cluster-web-78f8455bf7-k5dgs
Namespace:    default
Priority:     0
Node:         minikube/192.168.49.2
Start Time:   Tue, 27 Apr 2021 11:24:18 -0300
Labels:       app=airflow
              component=web
              pod-template-hash=78f8455bf7
              release=airflow-cluster
Annotations:  checksum/config-webserver-config: 68c0dbf55c6d894676b830341ba0a967597f78cebc5f97ae2101ae408502acf0
              checksum/secret-config: 82577e42641d1d5fe50e733304eca271a9d07f8d9a8b32d3cd9fa8326b15ce68
              cluster-autoscaler.kubernetes.io/safe-to-evict: true
Status:       Running
IP:           172.17.0.6
IPs:
  IP:           172.17.0.6
Controlled By:  ReplicaSet/airflow-cluster-web-78f8455bf7
Init Containers:
  check-db:
    Container ID:  docker://d1534ce427d784113ee5b8ed681c21b6135093c5ef5ceb659a6bf917cace0a45
    Image:         apache/airflow:2.0.2-python3.8
    Image ID:      docker-pullable://apache/airflow@sha256:1175f906a7979b85884f70f9ca4f719a24759dc76027879d49373a4768108923
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
    Args:
      bash
      -c
      exec timeout 60s airflow db check
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 27 Apr 2021 11:24:20 -0300
      Finished:     Tue, 27 Apr 2021 11:25:02 -0300
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      airflow-cluster-config  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'airflow-cluster-postgresql'>  Optional: false
      REDIS_PASSWORD:     
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from airflow-cluster-token-zpvfl (ro)
  wait-for-db-migrations:
    Container ID:  docker://6e50ef11ad34ef15ff4ae707ffa0be20a2bf22da5c429b4888f2993f0ceb283f
    Image:         apache/airflow:2.0.2-python3.8
    Image ID:      docker-pullable://apache/airflow@sha256:1175f906a7979b85884f70f9ca4f719a24759dc76027879d49373a4768108923
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
    Args:
      bash
      -c
      exec airflow db check-migrations -t 60
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 27 Apr 2021 11:25:03 -0300
      Finished:     Tue, 27 Apr 2021 11:26:16 -0300
    Ready:          True
    Restart Count:  0
    Environment Variables from:
      airflow-cluster-config  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'airflow-cluster-postgresql'>  Optional: false
      REDIS_PASSWORD:     
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from airflow-cluster-token-zpvfl (ro)
Containers:
  airflow-web:
    Container ID:  docker://8e2115aa39df5282713729f464a10570e27dcd5eeaaed1a97203e1e6e4420c94
    Image:         apache/airflow:2.0.2-python3.8
    Image ID:      docker-pullable://apache/airflow@sha256:1175f906a7979b85884f70f9ca4f719a24759dc76027879d49373a4768108923
    Port:          8080/TCP
    Host Port:     0/TCP
    Command:
      /usr/bin/dumb-init
      --
    Args:
      bash
      -c
      exec airflow webserver
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Tue, 27 Apr 2021 11:40:15 -0300
      Finished:     Tue, 27 Apr 2021 11:41:54 -0300
    Ready:          False
    Restart Count:  7
    Liveness:       http-get http://:web/health delay=10s timeout=5s period=10s #success=1 #failure=6
    Readiness:      http-get http://:web/health delay=10s timeout=5s period=10s #success=1 #failure=6
    Environment Variables from:
      airflow-cluster-config  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:  <set to the key 'postgresql-password' in secret 'airflow-cluster-postgresql'>  Optional: false
      REDIS_PASSWORD:     
    Mounts:
      /opt/airflow/webserver_config.py from webserver-config (ro,path="webserver_config.py")
      /var/run/secrets/kubernetes.io/serviceaccount from airflow-cluster-token-zpvfl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  webserver-config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  airflow-cluster-webserver-config
    Optional:    false
  airflow-cluster-token-zpvfl:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  airflow-cluster-token-zpvfl
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  18m                   default-scheduler  Successfully assigned default/airflow-cluster-web-78f8455bf7-k5dgs to minikube
  Normal   Created    18m                   kubelet            Created container check-db
  Normal   Started    18m                   kubelet            Started container check-db
  Normal   Pulled     18m                   kubelet            Container image "apache/airflow:2.0.2-python3.8" already present on machine
  Normal   Started    17m                   kubelet            Started container wait-for-db-migrations
  Normal   Pulled     17m                   kubelet            Container image "apache/airflow:2.0.2-python3.8" already present on machine
  Normal   Created    17m                   kubelet            Created container wait-for-db-migrations
  Normal   Killing    15m                   kubelet            Container airflow-web failed liveness probe, will be restarted
  Normal   Pulled     15m (x2 over 16m)     kubelet            Container image "apache/airflow:2.0.2-python3.8" already present on machine
  Normal   Created    15m (x2 over 16m)     kubelet            Created container airflow-web
  Normal   Started    15m (x2 over 16m)     kubelet            Started container airflow-web
  Warning  Unhealthy  13m (x10 over 15m)    kubelet            Liveness probe failed: Get "http://172.17.0.6:8080/health": dial tcp 172.17.0.6:8080: connect: connection refused
  Warning  Unhealthy  8m5s (x21 over 16m)   kubelet            Readiness probe failed: Get "http://172.17.0.6:8080/health": dial tcp 172.17.0.6:8080: connect: connection refused
  Warning  BackOff    3m1s (x12 over 5m1s)  kubelet            Back-off restarting failed container
```
#### Pod Logs
```console
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 484, in webserver
    monitor_gunicorn(gunicorn_master_proc.pid)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 445, in monitor_gunicorn
    GunicornMonitor(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 212, in start
    self._check_workers()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 236, in _check_workers
    sleep(1)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/webserver_command.py", line 434, in kill_proc
    gunicorn_master_proc.wait(timeout=30)
  File "/usr/local/lib/python3.8/subprocess.py", line 1083, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/lib/python3.8/subprocess.py", line 1800, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['gunicorn', '--workers', '4', '--worker-class', 'sync', '--timeout', '120', '--bind', '0.0.0.0:8080', '--name', 'airflow-webserver', '--pid', '/opt/airflow/airflow-webserver.pid', '--config', 'python:airflow.www.gunicorn_config', '--access-logfile', '-', '--error-logfile', '-', 'airflow.www.app:cached_app()']' timed out after 30 seconds
```

#### 

#### Port-Forward Logs

```console
Handling connection for 8080                                                                  
E0427 11:29:15.503293  219506 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 7e56c92749a1d78baf4388e0742ec49560f40a0924e47c4aabdbd1d91cb4d66
c, uid : exit status 1: 2021/04/27 14:29:15 socat[28337] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
Handling connection for 8080 
E0427 11:29:50.727702  219506 portforward.go:400] an error occurred forwarding 8080 -> 8080: error forwarding port 8080 to pod 7e56c92749a1d78baf4388e0742ec49560f40a0924e47c4aabdbd1d91cb4d66
c, uid : exit status 1: 2021/04/27 14:29:50 socat[29113] E connect(5, AF=2 127.0.0.1:8080, 16): Connection refused
```
#### Ports Usage
```console
$ sudo lsof -i -P -n | grep LISTEN
[...]
docker-pr  17076            root    4u  IPv4  175444      0t0  TCP 127.0.0.1:49153 (LISTEN)
docker-pr  17088            root    4u  IPv4  172940      0t0  TCP 127.0.0.1:49154 (LISTEN)
docker-pr  17102            root    4u  IPv4  173698      0t0  TCP 127.0.0.1:49155 (LISTEN)
docker-pr  17115            root    4u  IPv4  175490      0t0  TCP 127.0.0.1:49156 (LISTEN)
docker-pr  17127            root    4u  IPv4  173703      0t0  TCP 127.0.0.1:49157 (LISTEN)
kubectl   219506          acosta    8u  IPv4 1012471      0t0  TCP 127.0.0.1:8080 (LISTEN)
kubectl   219506          acosta    9u  IPv6 1012472      0t0  TCP [::1]:8080 (LISTEN)
```

#### Pods Status
``` console
$ kubectl get pods
NAME                                         READY   STATUS             RESTARTS   AGE
airflow-cluster-postgresql-0                 1/1     Running            0          28m
airflow-cluster-scheduler-7f69899966-jjblz   1/1     Running            2          28m
airflow-cluster-scheduler-7f69899966-q6pb2   1/1     Running            2          28m
airflow-cluster-web-78f8455bf7-k5dgs         0/1     CrashLoopBackOff   9          28m
```

### What are your Helm values?
```yaml
airflow:
  image:
    repository: apache/airflow
    tag: 2.0.2-python3.8
  executor: KubernetesExecutor
  config:
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"

scheduler:
  replicas: 2

web:
  replicas : 1

workers:
  enabled: false

flower:
  enabled: false

redis:
  enabled: false
```

### What is your Kubernetes version?
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

### What is your Helm version?
```console
$ helm version
version.BuildInfo{Version:"v3.5.2", GitCommit:"167aac70832d3a384f65f9745335e9fb40169dc2", GitTreeState:"dirty", GoVersion:"go1.15.7"}
$ helm ls
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
airflow-cluster default         1               2021-04-27 11:24:18.398306389 -0300 -03 deployed        airflow-8.0.9   2.0.1 
```

**Comment by ahayasic** [comment]
**UPDATE**

After 60 minutes and 17 restarts, finally, the web service pod is working. But it's still strange behavior

**Comment by thesuperzapper** [comment]
@ahayasic are you able to replicate this behaviour with a clean namespace?

**Comment by ahayasic** [comment]
@thesuperzapper, I tried using a namespace `airflow-namespace` with values

```yaml
apiVersion: v1
kind: Namespace
metadata:
    name: airflow-namespace
```

And the deployment worked well with `scheduler.replicas: 2`, but not `3` (even after 90 minutes and many restarts).

Increasing web server replicas didn't work at all.

**Comment by andormarkus** [comment]
Hi @ahayasic 

I dont experience this problem with the following config on v8.0.9 with Airflow v2.0.1
**values.yaml**
```yaml
airflow:
  executor: KubernetesExecutor
  fernetKey: "foobaaa"
  config:
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    AIRFLOW__CORE__LOAD_EXAMPLES: "True"

scheduler:
  replicas: 3
  nodeSelector:
    namespace: airflow

web:
  replicas: 1
  nodeSelector:
    namespace: airflow

  service:
    type: LoadBalancer
    externalPort: 80
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
      external-dns.alpha.kubernetes.io/hostname: ${web_url}

workers:
  enabled: false
  nodeSelector:
    namespace: airflow


postgresql:
  #  existingSecret: airflow-postgres-password
  enabled: false

externalDatabase:
  type: postgres
  host: ${database_host}
  port: 5432
  database: airflow
  user: postgres
  passwordSecret: "airflow-postgres-password"
  passwordSecretKey: "postgresql-password"

flower:
  enabled: false

redis:
  enabled: false
```

**Terraform code to deploy it**
```hcl
resource "helm_release" "airflow" {
  repository = "https://airflow-helm.github.io/charts"
  chart      = "airflow"
  name       = "airflow"
  version    = "8.0.9"
  namespace  = "airflow"
  wait       = false
  values     = [templatefile("${path.root}/helm/airflow.yml", {
    web_url       = "airflow.com"
    database_host = module.db_default.db_instance_address
  })]
}
```

**Comment by thesuperzapper** [comment]
@ahayasic are you still having this issue?

**Comment by ahayasic** [comment]
Apparently no! I was not using the chart for a while, but I did some tests using version 8.3.1 and everything worked fine. Thanks!

**Comment by thesuperzapper** [comment]
@ahayasic I think this is still an issue, but I think it depends on your Service/Ingress being "sticky" with sessions, see https://github.com/airflow-helm/charts/issues/72#issuecomment-835361440.
