### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/logs/hello_world/hello_task/2021-05-24T14:48:14.877499+00:00/1.log'

### ISSUE THREAD

**Issue by nike4122** [airflow-helm/charts#212]
Hi , I have done the setup of airflow using airflow-helm charts in AKS . I have configured persistent volume for dags and logs. But worked pod is failed to start after configured PV for logs. I am getting below error logs from the worker pod,

BACKEND=postgresql+psycopg2
DB_HOST=apache-airflow-postgresql
DB_PORT=5432

WARNING:root:OSError while attempting to symlink the latest log directory
[2021-05-24 14:48:41,771] {dagbag.py:451} INFO - Filling up the DagBag from /opt/airflow/dags/hello_world.py
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 225, in task_run
    ti.init_run_context(raw=args.raw)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2016, in init_run_context
    self._set_context(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 54, in _set_context
    set_context(self.log, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/logging_mixin.py", line 174, in set_context
    handler.set_context(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 56, in set_context
    local_loc = self._init_file(ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/log/file_task_handler.py", line 258, in _init_file
    os.chmod(full_path, 0o666)
PermissionError: [Errno 1] Operation not permitted: '/opt/airflow/logs/hello_world/hello_task/2021-05-24T14:48:14.877499+00:00/1.log'

Below pod are running in K8s,
apache-airflow-postgresql-0                                        1/1     Running     
apache-airflow-scheduler-55cc877575-wtlqn              1/1     Running   0          20h
apache-airflow-web-6f9dcc5fff-tft5b                           1/1     Running   0          20h
**helloworldhellotask.085186513e8f4012a3aa39f37fc5a967   0/1     Error     0          104m**

 Airflow Ver. -  2.0.2 with embedded postgresql.
 Airflow executor type - **KubernetesExecutor**

**Comment by thesuperzapper** [comment]
@nike4122 what type of persistent volume are you using for logs? Does it support `ReadWriteMany`?

**Comment by nike4122** [comment]
@thesuperzapper We are using "AzureFiles" which supports ReadWriteMany.   
We can see other logs in the same pv , 
- dag_processor_manager
- scheduler

When we are executing a dag , a new folder is creating for particular job inside the PV, but 0 B of log data.

FOLDER PATH - hello_world/hello_task/2021-06-02T203613.037840+0000/1.log (0 B)

**Comment by thesuperzapper** [comment]
@nike4122 I am almost certain that this is caused by not having `fsGroup` set in your securityContext.

Very soon, there will be a new global `airflow.extraSecurityContext` value with `{fsGroup: 0}` as default.
(See PR https://github.com/airflow-helm/charts/pull/367 for more info).

This will be in `8.5.0` of the chart, to be released today/tomorrow.
