### ISSUE TITLE
azure.core.exceptions.ResourceExistsError: The specified blob already exists.

### ISSUE THREAD

**Issue by nike4122** [airflow-helm/charts#217]
AIrflow Ver - 2.0.2
Hem Chart - 8.1.3 
Platform - AKS 
Executor - KubernatesExecutor 

We have enabled remote logging for persist the log in airflow 2.0.2.  Below are the configuration we have done for this,

    AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
    AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "wasb-airflow-logs"
    AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: wasb_default  # remote_logging
    AIRFLOW__CORE__LOGGING_LEVEL: "DEBUG"
    AIRFLOW__CORE__FAB_LOGGING_LEVEL: "DEBUG"
    AIRFLOW__CORE__LOG_FILENAME_TEMPLATE: "{{ run_id }}/{{ ti.dag_id }}/{{ ti.task_id }}/{{ ts }}/{{ try_number }}.log"

But DAGs are failing with below error which we are getting in worker pod,

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 235, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 64, in _run_task_by_selected_method
    _run_task_by_local_task_job(args, ti)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 124, in _run_task_by_local_task_job
    logging.shutdown()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 2123, in shutdown
    h.close()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/log/wasb_task_handler.py", line 103, in close
    self.wasb_write(log, remote_loc, append=True)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/log/wasb_task_handler.py", line 189, in wasb_write
    self.hook.load_string(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 217, in load_string
    self.upload(container_name, blob_name, string_data, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/microsoft/azure/hooks/wasb.py", line 274, in upload
    return blob_client.upload_blob(data, blob_type, length=length, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_blob_client.py", line 685, in upload_blob
    return upload_block_blob(**options)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 157, in upload_block_blob
    process_storage_error(error)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_shared/response_handlers.py", line 150, in process_storage_error
    error.raise_with_traceback()
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 218, in raise_with_traceback
    raise super(AzureError, self).with_traceback(self.exc_traceback)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_upload_helpers.py", line 94, in upload_block_blob
    return client.upload(
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/storage/blob/_generated/operations/_block_blob_operations.py", line 231, in upload
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "/home/airflow/.local/lib/python3.8/site-packages/azure/core/exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceExistsError: The specified blob already exists.
RequestId:3fc5536d-d01e-0031-610f-5985b6000000
Time:2021-06-04T06:59:24.9765326Z
ErrorCode:BlobAlreadyExists

**Comment by thesuperzapper** [comment]
@nike4122 are you still having this issue?

**Comment by nike4122** [comment]
@thesuperzapper we are not seeing this error for now. but we didn't apply any fix for this.
