### ISSUE TITLE
Error in database init and google OAuth login

### ISSUE THREAD

**Issue by shubhamc183** [airflow-helm/charts#36]
**Airflow database init command is throwing some `WARNING` logs and `users` table not created.**

I am using AWS SQS instead of Redis as a broker and have modified the helm chart accordingly. As SQS needs `pycurl` python package I took the [official Dockerfile](https://github.com/apache/airflow/blob/master/Dockerfile) and made these changes as [`pycurl` have OS-level dependency](https://github.com/celery/celery/issues/4654)

```
 ARG RUNTIME_APT_DEPS="\
+       gcc \
+       libcurl4-gnutls-dev \
+       librtmp-dev \
+       python3-pycurl \
        apt-transport-https \
        apt-utils \
        ca-certificates \
```
The connection with Postgres DB and SQS is working fine.

**SOME ENVIRONMENT VARIABLES**
```
AIRFLOW_VERSION=2.0.0.dev0
BROKER_CONNECTION_CMD=echo -n "sqs://${AWS_ACCESS_KEY_ID}:${AWS_SECRET_ACCESS_KEY}@"
AIRFLOW__CELERY__BROKER_URL_CMD=bash -c 'eval "$BROKER_CONNECTION_CMD"'
AIRFLOW__CELERY__RESULT_BACKEND_CMD=bash -c 'eval "$DATABASE_CELERY_CMD"'
AIRFLOW__WEBSERVER__AUTHENTICATE=True
AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.google_auth
AIRFLOW__GOOGLE__DOMAIN=XXX.com
AIRFLOW__GOOGLE__CLIENT_SECRET=XXXXXXXXXXXXXXX
AIRFLOW__GOOGLE__OAUTH_CALLBACK_ROUTE=/oauth2callback
AIRFLOW__GOOGLE__CLIENT_ID=XXXXXXXXXXXXXXX.apps.googleusercontent.com
```

**Airflow with Google OAuth but when I'm login into Airflow. I am getting an error that `users` tables don't exist.**

```
[2020-12-11 13:26:09,854] {app.py:1892} ERROR - Exception on /oauth2callback [GET]
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedTable: relation "users" does not exist
LINE 2: FROM users 
             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/contrib/auth/backends/google_auth.py", line 172, in oauth_callback
    models.User.username == username).first()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3402, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3176, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3508, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3533, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedTable) relation "users" does not exist
LINE 2: FROM users 
             ^

[SQL: SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.superuser AS users_superuser 
FROM users 
WHERE users.username = %(username_1)s 
 LIMIT %(param_1)s]
[parameters: {'username_1': 'Shubham Choudhary', 'param_1': 1}]
(Background on this error at: http://sqlalche.me/e/13/f405)
```

**I also see this in the scheduler logs**

INFO  [alembic.runtime.migration] Running upgrade 1968acfc09e3 -> 2e82aab8ef20, rename user table

**After running airflow db init I have all these tables created.**
```
                        List of relations
 Schema |             Name              | Type  |      Owner      
--------+-------------------------------+-------+-----------------
 public | ab_permission                 | table | airflow_qa_user
 public | ab_permission_view            | table | airflow_qa_user
 public | ab_permission_view_role       | table | airflow_qa_user
 public | ab_register_user              | table | airflow_qa_user
 public | ab_role                       | table | airflow_qa_user
 public | ab_user                       | table | airflow_qa_user
 public | ab_user_role                  | table | airflow_qa_user
 public | ab_view_menu                  | table | airflow_qa_user
 public | alembic_version               | table | airflow_qa_user
 public | celery_taskmeta               | table | airflow_qa_user
 public | celery_tasksetmeta            | table | airflow_qa_user
 public | connection                    | table | airflow_qa_user
 public | dag                           | table | airflow_qa_user
 public | dag_code                      | table | airflow_qa_user
 public | dag_pickle                    | table | airflow_qa_user
 public | dag_run                       | table | airflow_qa_user
 public | dag_tag                       | table | airflow_qa_user
 public | import_error                  | table | airflow_qa_user
 public | job                           | table | airflow_qa_user
 public | log                           | table | airflow_qa_user
 public | rendered_task_instance_fields | table | airflow_qa_user
 public | sensor_instance               | table | airflow_qa_user
 public | serialized_dag                | table | airflow_qa_user
 public | sla_miss                      | table | airflow_qa_user
 public | slot_pool                     | table | airflow_qa_user
 public | task_fail                     | table | airflow_qa_user
 public | task_instance                 | table | airflow_qa_user
 public | task_reschedule               | table | airflow_qa_user
 public | variable                      | table | airflow_qa_user
 public | xcom                          | table | airflow_qa_user
(30 rows)
```
**My Scheduler and Worker the airflow points to `apache-airflow @ file:///opt/airflow` whereas in Web `apache-airflow==1.10.12`**

**I am assuming that I am modifying the wrong Dockerfile!!** 

**What is your Kubernetes Version?**:
```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:
```
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
```

**Comment by thesuperzapper** [comment]
@shubhamc183 are you still having this issue after version `8.0.0` of the chart (which natively supports airflow 2.0)?

**Comment by shubhamc183** [comment]
@thesuperzapper I'm not working or using this for the last 3 months so I cannot say.
