### ISSUE TITLE
edit connection causes page crash

### ISSUE THREAD

**Issue by javamonkey79** [airflow-helm/charts#413]
**What is the bug?**

When I click on edit connection, I get the following exception:
```
Something bad has happened.
Please consider letting us know by creating a bug report using GitHub.

Python version: 3.8.10
Airflow version: 2.1.2
Node: airflow-new-web-6784f5c49c-98gg5
-------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/airflow/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_appbuilder/security/decorators.py", line 109, in wraps
    return f(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_appbuilder/views.py", line 602, in edit
    widgets = self._edit(pk)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_appbuilder/baseviews.py", line 1233, in _edit
    form = self.edit_form.refresh(obj=item)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_appbuilder/forms.py", line 329, in refresh
    form = self(obj=obj)
  File "/home/airflow/.local/lib/python3.8/site-packages/wtforms/form.py", line 208, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/flask_wtf/form.py", line 87, in __init__
    super(FlaskForm, self).__init__(formdata=formdata, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/wtforms/form.py", line 274, in __init__
    self.process(formdata, obj, data=data, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/wtforms/form.py", line 126, in process
    if obj is not None and hasattr(obj, name):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 365, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 262, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/home/airflow/.local/lib/python3.8/site-packages/cryptography/fernet.py", line 194, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**What version of the chart are you using?**:

I am using version `8.5.2`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

**Please copy your custom Helm values file:**

```yaml
airflow:
  config:
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: True
    AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE: 1000
    AIRFLOW__CELERY__CELERY_CONCURRENCY: 16
    AIRFLOW__CELERY__WORKER_CONCURRENCY: 16
    AIRFLOW__SMTP__SMTP_HOST: mail-relay.some-domain.company.com
    AIRFLOW__SMTP__SMTP_STARTTLS: False
    AIRFLOW__SMTP__SMTP_MAIL_FROM: new-airflow-dev@company.com
    AIRFLOW__SMTP__SMTP_PORT: 1465
    AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: False
    AIRFLOW__SCHEDULER__RUN_DURATION: 21600
    AIRFLOW__WEBSERVER__BASE_URL: http://new-airflow.team-dev.company.com:8080/
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
    PIP_INDEX_URL: https://some-nexus-url/repository/company-pypi-group/simple
  extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-envvars
          key: fernet-key
  variables:
    - key: "environment"
      value: "dev"
    - key: "foo.alert_emails"
      value: "['something@company.com']"
  connections:
    - id: databricks_default
      type: databricks
      token: 123
      host: company.cloud.databricks.com
      extra: '{"host": "company.cloud.databricks.com", "token":"123"}'  
web:
  initialDelaySeconds: 30
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: new-airflow.team-dev.company.com
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb  
dags:
  gitSync:
    repo: https://oauth2:123@gitlab.some-domain.company.com/company/team-airflow.git
    branch: dev
    enabled: true
    syncWait: 60
persistence:
  enabled: true
  storageClass: gp2
  size: 10Gi
workers:
  replicas: 2
postgresql:
  postgresqlExtendedConf:
    maxConnections: "1000"
```

**Comment by thesuperzapper** [comment]
@javamonkey79 are you sure that your `fernet-key` key in `Secret/secret-envvars` is correctly base64 encoded? 

Be aware that a Kubernetes Secret requires you to base64 encode the `data` field, so in effect, you will need to double base64 encode your string `fernet-key` key.

You can generate a fernet key with the following command:
(NOTE: to use this in a Secret `data` field you will need to base64 encode the OUTPUT of this as well)
```python
python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
```

**Comment by thesuperzapper** [comment]
@javamonkey79 can you also provide the logs of the `xxxx-sync-connections` Deployment?

**Comment by javamonkey79** [comment]
> @javamonkey79 are you sure that your `fernet-key` key in `Secret/secret-envvars` is correctly base64 encoded?
> 
> Be aware that a Kubernetes Secret requires you to base64 encode the `data` field, so in effect, you will need to double base64 encode your string `fernet-key` key.
> 
> You can generate a fernet key with the following command:
> (NOTE: to use this in a Secret `data` field you will need to base64 encode the OUTPUT of this as well)
> 
> ```python
> python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
> ```

Hey @thesuperzapper , that's a good callout. I did not know it needed to be base64 encoded again. I also tried using the fernetKey value, directly in the values file, instead of in secrets and got the same result. Do you know if that should be base64 encoded too? 

I'll try base64 encoding the key and running it all again tomorrow. If it still does not work, I'll attach logs, as requested. 

Thanks for your help!

**Comment by thesuperzapper** [comment]
@javamonkey79 the `airflow.fernetKey` value only needs to be encoded once.

**Comment by javamonkey79** [comment]
Hey @thesuperzapper , thanks for your help thus far. I've had a chance to do some more testing. The issue is still unresolved for me. 

I've tried base64 encoding the key, as you suggested:
```
python -c "from cryptography.fernet import Fernet; import base64; FERNET_KEY = Fernet.generate_key(); print(base64.b64encode(FERNET_KEY))"
```

I then put this into my secrets file (this is old, and the key no longer used, so, ok to post here):
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-envvars
type: Opaque
stringData:
  fernet-key: U2IyaU82dS1IMVRPTzNPNGJVMkV3RVhZQWs3bVE2cDNWRTNxSUtXUms3WT0=
```

With this approach, I get a new error:
```
Could not create Fernet object: Fernet key must be 32 url-safe base64-encoded bytes
```

So, I tried setting just the airflow.fernetKey using the method described in the example values file:
```
python -c "from cryptography.fernet import Fernet; FERNET_KEY = Fernet.generate_key().decode(); print(FERNET_KEY)"
```

Again, old key:
```
  fernetKey: "hFm9VaCGyQa_Z460_Cs-j_BakkB2Ia5IT_wwAa69j2A="
```

This gets me the same error as before, which is the same in the sync-connections log too:
```
➜  Downloads k8 logs airflow-new-sync-connections-5b678b8995-thwqf -c sync-airflow-connections                                                                                 <aws:dwh-dev>
[2021-08-31 22:16:15,009] {sync_connections.py:310} INFO - BEGIN: airflow connections sync
Traceback (most recent call last):
  File "/mnt/scripts/sync_connections.py", line 326, in <module>
    main(sync_forever=True)
  File "/mnt/scripts/sync_connections.py", line 99, in main
    sync_with_airflow()
  File "/mnt/scripts/sync_connections.py", line 320, in sync_with_airflow
    sync_all_connections(connection_wrappers=VAR__CONNECTION_WRAPPERS)
  File "/mnt/scripts/sync_connections.py", line 312, in sync_all_connections
    sync_connection(connection_wrapper)
  File "/mnt/scripts/sync_connections.py", line 286, in sync_connection
    if compare_connections(c_new, c_old):
  File "/mnt/scripts/sync_connections.py", line 265, in compare_connections
    and c1.extra == c2.extra
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 365, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 262, in get_extra
    return fernet.decrypt(bytes(self._extra, 'utf-8')).decode()
  File "/home/airflow/.local/lib/python3.8/site-packages/cryptography/fernet.py", line 194, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken
```

I get this same result, when I don't set anything with fernet at all (eg using the default from the values file). So, it seems like maybe there is more going on here?

**Comment by javamonkey79** [comment]
@thesuperzapper after tearing down most of my values file, I ran install again and noticed that connections that I'd removed remained. Sure enough, the PVC for postgres remained. After deleting it, this issue is now resolved. I think that the default fernetKey was used, during my first setup, and since that key was lost, but, the data remained, it could never decode properly.

**Comment by piyush-daga** [comment]
@thesuperzapper Should this behaviour be documented in [https://github.com/airflow-helm/charts/tree/main/charts/airflow#how-to-create-airflow-connections](url) or rather #https://github.com/airflow-helm/charts/blob/main/charts/airflow/values.yaml#L31

I faced the same issue and resolved it by deleting the connections encoded by the old Fernet Key (initial deployment was with defaults).

Does this also mean that to introduce a new fernet key for any reason we need to delete and re-enter all of our connections?

**Comment by thesuperzapper** [comment]
@piyush-daga I agree that we should document that connections/variables/etc are not removed when they are unset from `airflow.connections`.

__Regarding the process to change your fernet key, you can either:__
1. OPTION 1: Manually delete and recreate your connections 
    - (I just tested, and the `airflow.connections` will error if the connections have the wrong fernet_key, and be unable to update them)
2. OPTION 2: Follow airflow's ["Rotating encryption keys"](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html#rotating-encryption-keys) guide

**Comment by thesuperzapper** [comment]
I have raised an issue for what to do about `airflow.connections` failing on `fernetKey` update: https://github.com/airflow-helm/charts/issues/439

**Comment by emilianomoscato** [comment]
Hello Everybody,

We're facing this error because we generated an `airflow.connections` entry and then removed without removing connection from Connections UI.
Now we have Connections UI page broken throwing invalid token error. How can we fix it? I don't know how to delete connection without UI.
We are running Airflow 2.1.4 with helm chart 8.5.3.

Thanks a lot for any advise on this!

**Comment by thesuperzapper** [comment]
@emilianomoscato If the error you are seeing is `cryptography.fernet.InvalidToken`, you need to either:

1. OPTION 1: If you know your `old_fernet_key`, you can use the ["Rotating encryption keys"](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html#rotating-encryption-keys) guide from Airflow.
2. OPTION 2: Remove the connections from the database manually:
     - Hopefully, you can use `airflow connections delete MY_CONNECTION_ID` from the CLI
     - Alternatively, if that fails, you may need to drop them from your PostgresSQL DB using SQL directly

**Comment by emilianomoscato** [comment]
@thesuperzapper thanks for your response.

> @emilianomoscato If the error you are seeing is `cryptography.fernet.InvalidToken`, you need to either:
> 
> 1. OPTION 1: If you know your `old_fernet_key`, you can use the ["Rotating encryption keys"](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html#rotating-encryption-keys) guide from Airflow.

I didn't change fernet_key, at least not consciously. So I don't know where to find it. 

> 2. OPTION 2: Remove the connections from the database manually:
>    
>    * Hopefully, you can use `airflow connections delete MY_CONNECTION_ID` from the CLI
>    * Alternatively, if that fails, you may need to drop them from your PostgresSQL DB using SQL directly

I could delete the entry from CLI! 
Unfurtunatelly, when trying to list connections InvalidToken error remains

```
$ airflow connections delete aws_airflow_dev
Successfully deleted connection with `conn_id`=aws_airflow_dev

$ airflow connections list
Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 315, in _wrapper
    f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/connection_command.py", line 76, in connections_list
    conns = query.all()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 100, in instances
    cursor.close()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in instances
    rows = [proc(row) for row in fetch]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 80, in <listcomp>
    rows = [proc(row) for row in fetch]
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/loading.py", line 601, in _instance
    state.manager.dispatch.load(state, context)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/mapper.py", line 3397, in _event_on_load
    instrumenting_mapper._reconstructor(state.obj())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 150, in on_db_load
    if self.password:
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 365, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 235, in get_password
    return fernet.decrypt(bytes(self._password, 'utf-8')).decode()
  File "/home/airflow/.local/lib/python3.8/site-packages/cryptography/fernet.py", line 194, in decrypt
    raise InvalidToken
cryptography.fernet.InvalidToken

```

Should I recreate pod or make a `helm upgrade`?

**Comment by thesuperzapper** [comment]
@emilianomoscato so you solved your issue by removing the connection with the cli?

**Comment by emilianomoscato** [comment]
@thesuperzapper No, I didin't I deleted the connection from cli, but InvalidToken error remains when I query the connection list also from Web UI (Admin -> connections) or from CLI `airflow connections list` command.

**Comment by thesuperzapper** [comment]
@emilianomoscato clearly you need to manually remove the broken connections from your metadata DB, you can do this a few ways:
1. Manually remove the problematic rows from your Postgres DB using `airflow db shell`  (or manually starting a `psql` command)
2. If you are willing to fully clear all your database information (including past dag runs), you can use `airflow db reset`

**Comment by emilianomoscato** [comment]
Thanks for your help @thesuperzapper 

I would like to identificate which the broken connections are. Do you know how I would do it? Maybe adding some debugging information into the scheduler or de web pod?

**Comment by thesuperzapper** [comment]
@emilianomoscato adding a new debug log would require a change to airflow's WebUI I think.

But honestly, we should probably raise an issue about how connections are handled in the UI. If a connection has the wrong fernet key, they should probably have a "warning" icon beside them, and grey out the edit button.

**Comment by emilianomoscato** [comment]
Hello Everybody,

Just for people who get to this thread with similar problem. Yesterday we solved the connections list crash issue.

From sql we got all the connections:
`SELECT conn_id FROM connection;`

then for every connection I run:
`airflow connections get <conn_id>`

and for every connection that throws broken output:
`airflow connections delete <con_id>`

After removing all that was broken, `airflow connections list` and Admin -> Connections from Web UI worked again.

**Comment by stevenkitter** [comment]
@emilianomoscato Everytime i restart the helm chart, I must delete all connections. What a pity.
