### ISSUE TITLE
Where are the logs for DAG loading?

### ISSUE THREAD

**Issue by javamonkey79** [airflow-helm/charts#415]
My DAGs are failing to load, with the following error:
```
Broken DAG: [/opt/airflow/dags/repo/ppm/ppm.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

I've ran this command, to get all logs:
```
for pod in `kubectl get pods -o jsonpath="{range .items[*]}{'\n'}{.metadata.name}{end}"`; do for container in `kubectl get pods $pod -o jsonpath="{range .spec.containers[*]}{'\n'}{.name}{end}"`; do kubectl logs $pod -c $container >> logs.txt; done; done;
```

And, I can't find any errors in the logs. 

Where are the logs for DAG loading?

**Comment by thesuperzapper** [comment]
@javamonkey79 you should just be able to see them in the Sheduler pod logs?

What do you see when you look at those?

**Comment by javamonkey79** [comment]
@thesuperzapper I don't seem them in the scheduler pod logs. I did find DAG loading logs in:
airflow-new-worker-0 -> dags-git-sync

Command for someone else, in case it helps:
```
for pod in `kubectl get pods -o jsonpath="{range .items[*]}{'\n'}{.metadata.name}{end}"`; do for container in `kubectl get pods $pod -o jsonpath="{range .spec.containers[*]}{'\n'}{.name}{end}"`; do echo "$pod -> $container" >> logs.txt && kubectl logs $pod -c $container >> logs.txt; done; done;
```
