### ISSUE TITLE
error in DAG loading - possible old schema?

### ISSUE THREAD

**Issue by javamonkey79** [airflow-helm/charts#417]
**What is the bug?**

When I check the logs, I notice the following exception
```
ERROR [airflow.models.dagbag.DagBag] Failed to import: /opt/airflow/dags/repo/ads/ads_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column variable.description does not exist
LINE 1: ....id AS variable_id, variable.key AS variable_key, variable.d...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/repo/ads/ads_pipeline.py", line 11, in <module>
    env = get_environment().upper()
  File "/home/airflow/.local/lib/python3.8/site-packages/edmunds/airflow/util/environment.py", line 11, in get_environment
    env = Variable.get(ENVIRONMENT).upper()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 135, in get
    var_val = Variable.get_variable_from_secrets(key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/variable.py", line 204, in get_variable_from_secrets
    var_val = secrets_backend.get_variable(key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/secrets/metastore.py", line 64, in get_variable
    var_value = session.query(Variable).filter(Variable.key == key).first()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column variable.description does not exist
LINE 1: ....id AS variable_id, variable.key AS variable_key, variable.d...
```

**What version of the chart are you using?**:

I am using version `8.5.2`

**What is your Kubernetes Version?**:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.13-eks-8df270", GitCommit:"8df2700a72a2598fa3a67c05126fa158fd839620", GitTreeState:"clean", BuildDate:"2021-07-31T01:36:57Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
```

**What is your Helm version?**:

```console
$ helm version
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"dirty", GoVersion:"go1.16.3"}
```

**Please copy your custom Helm values file:**

```yaml
airflow:
  config:
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: True
    AIRFLOW__CORE__SQL_ALCHEMY_POOL_SIZE: 1000
    AIRFLOW__CELERY__CELERY_CONCURRENCY: 16
    AIRFLOW__CELERY__WORKER_CONCURRENCY: 16
    AIRFLOW__SMTP__SMTP_HOST: mail-relay.some-domain.company.com
    AIRFLOW__SMTP__SMTP_STARTTLS: False
    AIRFLOW__SMTP__SMTP_MAIL_FROM: new-airflow-dev@company.com
    AIRFLOW__SMTP__SMTP_PORT: 1465
    AIRFLOW__SCHEDULER__CATCHUP_BY_DEFAULT: False
    AIRFLOW__SCHEDULER__RUN_DURATION: 21600
    AIRFLOW__WEBSERVER__BASE_URL: http://new-airflow.team-dev.company.com:8080/
    AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: 60
    PIP_INDEX_URL: https://some-nexus-url/repository/company-pypi-group/simple
  extraEnv:
    - name: AIRFLOW__CORE__FERNET_KEY
      valueFrom:
        secretKeyRef:
          name: secret-envvars
          key: fernet-key
  variables:
    - key: "environment"
      value: "dev"
    - key: "foo.alert_emails"
      value: "['something@company.com']"
  connections:
    - id: databricks_default
      type: databricks
      token: 123
      host: company.cloud.databricks.com
      extra: '{"host": "company.cloud.databricks.com", "token":"123"}'  
web:
  initialDelaySeconds: 30
  service:
    type: LoadBalancer
    annotations:
      external-dns.alpha.kubernetes.io/hostname: new-airflow.team-dev.company.com
      service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
      service.beta.kubernetes.io/aws-load-balancer-type: nlb  
dags:
  gitSync:
    repo: https://oauth2:123@gitlab.some-domain.company.com/company/team-airflow.git
    branch: dev
    enabled: true
    syncWait: 60
persistence:
  enabled: true
  storageClass: gp2
  size: 10Gi
workers:
  replicas: 2
postgresql:
  postgresqlExtendedConf:
    maxConnections: "1000"
```

**Comment by javamonkey79** [comment]
Strangely enough, I get an error in the UI as well, but, it is different:
```
Broken DAG: [/opt/airflow/dags/repo/ads/ads_pipeline.py] Traceback (most recent call last):
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```

**Comment by javamonkey79** [comment]
OK, so, I think the first error is a red herring. Even though the error is thrown, I think airflow upgrades it's db and then stabilizes. As far as I can tell. 

For my second error, it was a bit hard to tell, but, I have some code like this in my DAGs:
```
'email': Variable.get('alert_emails', deserialize_json=True),
```

And the corresponding variable looked like this:
```
"['foo@bar.com','baz@bat.com']"
```

Airflow 1.x handled this just fine. Well, it turns out, 2.x does not. Since it is not really valid json, it failed. But, it is not super obvious _how_ it was failing.
