### ISSUE TITLE
Task is in the 'None' state which is not a valid state for execution

### ISSUE THREAD

**Issue by gowdra01** [airflow-helm/charts#435]
in one of our env we can't run any dags unfortunately it throws the error

```Task is in the 'None' state which is not a valid state for execution```

I am not sure how to solve this any idea how? @thesuperzapper  can you pls help

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/75704248/134431510-8eede028-9b52-425c-a1ed-9b2bbc6a02db.png">

I am seeing some exceptions in the scheduler logs. do you know what it means ? web logs are ok

```
[2021-09-22 23:36:38,247] {scheduler_job.py:993} INFO - Figuring out tasks to run in Pool(name=default_pool) with 124 ope
n slots and 1 task instances ready to be queued
[2021-09-22 23:36:38,247] {scheduler_job.py:1021} INFO - DAG yellowbrick_reports has 0/16 running and queued tasks
[2021-09-22 23:36:38,247] {scheduler_job.py:1086} INFO - Setting the following tasks to queued state:
        <TaskInstance: yellowbrick_reports.yb_prod_sac_fis_rw 2021-09-22 23:36:38.237592+00:00 [scheduled]>
[2021-09-22 23:36:38,249] {scheduler_job.py:1128} INFO - Sending TaskInstanceKey(dag_id='yellowbrick_reports', task_id='y
b_prod_sac_fis_rw', execution_date=datetime.datetime(2021, 9, 22, 23, 36, 38, 237592, tzinfo=Timezone('UTC')), try_number
=1) to executor with priority 8 and queue default
[2021-09-22 23:36:38,249] {base_executor.py:82} INFO - Adding to queue: ['airflow', 'tasks', 'run', 'yellowbrick_reports'
, 'yb_prod_sac_fis_rw', '2021-09-22T23:36:38.237592+00:00', '--local', '--pool', 'default_pool', '--subdir', '/opt/airflo
w/dags/dags/billings/yb_billings.py']
[2021-09-22 23:36:38,300] {scheduler_job.py:1222} INFO - Executor reports execution of yellowbrick_reports.yb_prod_sac_fi
s_rw execution_date=2021-09-22 23:36:38.237592+00:00 exited with status queued for try_number 1
[2021-09-22 23:36:38,333] {dagrun.py:459} ERROR - Deadlock; marking run <DagRun yellowbrick_reports @ 2021-09-22 23:36:37
.001066+00:00: manual__2021-09-22T23:36:37.001066+00:00, externally triggered: True> failed
[2021-09-22 23:36:46,274] {scheduler_job.py:1222} INFO - Executor reports execution of yellowbrick_reports.yb_prod_sac_fi
s_rw execution_date=2021-09-22 23:36:38.237592+00:00 exited with status success for try_number 1
[2021-09-22 23:36:47,330] {scheduler_job.py:964} INFO - 1 tasks up for execution:
        <TaskInstance: yellowbrick_reports.yb_prod_sac_fis_rw 2021-09-22 23:36:47.321092+00:00 [scheduled]>
```

```
W

 File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 370, in _run_processor_ma
nager
    processor_manager.start()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 610, in start
    return self._run_parsing_loop()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 677, in _run_parsing_loop
    self._find_zombies()  # pylint: disable=no-value-for-parameter
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/dag_processing.py", line 1136, in _find_zombies
    session.query(TI, DM.fileloc)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exceptio

    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exceptio
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 206, in execute
    res = self._query(query)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/cursors.py", line 319, in _query
    db.query(q)
  File "/home/airflow/.local/lib/python3.8/site-packages/MySQLdb/connections.py", line 259, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during qu
ery')
[SQL: SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_i
nstance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start
_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_insta
nce_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instan
ce.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_ins
tance_job_id, task_instance.pool AS task_instance_pool, task_instance.pool_slots AS task_instance_pool_slots, task_instan
ce.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator A
S task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance.queued_by_job_id AS task_
instance_queued_by_job_id, task_instance.pid AS task_instance_pid, task_instance.executor_config AS task_instance_executo
r_config, task_instance.external_executor_id AS task_instance_external_executor_id, dag.fileloc AS dag_fileloc
FROM task_instance INNER JOIN job ON task_instance.job_id = job.id AND job.job_type IN (%s) INNER JOIN dag ON task_instan
ce.dag_id = dag.dag_id
WHERE task_instance.state = %s AND (job.state != %s OR job.latest_heartbeat < %s)]
[parameters: ('LocalTaskJob', 'running', 'running', datetime.datetime(2021, 9, 22, 23, 19, 49, 276257))]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-09-22 23:24:50,147] {dag_processing.py:401} WARNING - DagFileProcessorManager (PID=137) exited with exit code 1 - r
e-launching
[2021-09-22 23:24:50,150] {dag_processing.py:254} INFO - Launched DagFileProcessorManager with pid: 148
/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:342 DeprecationWarning: The base_log_folder opt
ion in [core] has been moved to the base_log_folder option in [logging] - the old setting has been used, but please updat
e your config.
/home/airflow/.local/lib/python3.8/site-packages/airflow/configuration.py:342 DeprecationWarning: The dag_processor_manag
er_log_location option in [core] has been moved to the dag_processor_manager_log_location option in [logging] - the old s
etting has been used, but please update your config.
[2021-09-22 23:24:50,158] {settings.py:52} INFO - Configured default timezone Timezone('UTC')
```

**Comment by thesuperzapper** [comment]
@gowdra01 It looks like you are losing connection to your MySQL:
```
sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (2013, 'Lost connection to MySQL server during qu
ery')
```

Possibly its overloaded? (Check on the DB end?)

**Comment by gowdra01** [comment]
is that the reason the dags are going to the none state ?

**Comment by thesuperzapper** [comment]
@gowdra01 The information about the current state of dags is stored in the DB, so I imagine the DB being unavailable would cause `None` state.

You might want to try using Postgress, as it's really what Airflow is designed with (especially with the new PgBouncer feature in [`8.5.X`](https://github.com/airflow-helm/charts/blob/main/charts/airflow/CHANGELOG.md#850---2021-08-19) of the chart).

**Comment by gowdra01** [comment]
Hi @thesuperzapper 
can you please let me know I am seeing this below error in one of our airflow environements what could be the issue?

```[2021-11-16 04:33:50,612] {dagrun.py:459} ERROR - Deadlock; marking run <DagRun yellowbrick_reports @ 2021-11-16 04:33:49.116086+00:00: manual__2021-11-16T04:33:49.116086+00:00, externally triggered: True> failed```
