### ISSUE TITLE
"check-db" init-container prevents kubernetes from using side-car pgbouncer

### ISSUE THREAD

**Issue by minnieshi** [airflow-helm/charts#464]
## What version of the chart are you using?

I am using version `8.5.2` of this chart.

## What version of Kubernetes are you using?

```console
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:15:16Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.11", GitCommit:"0cc86139598f54b72130881efa5b77b78acf3c39", GitTreeState:"clean", BuildDate:"2021-10-09T03:57:17Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}
```

## What version of Helm are you using?

```console
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```

## What are your custom helm values?

<details>
<summary>click to expand</summary>

```yaml
imageCredentials:
  registry: registry.hub.docker.com
airflow:
  legacyCommands: false
  fernetKey: "blah"
  webserverSecretKey: "blah"
  service:
    annotations: {}
    sessionAffinity: "None"
    sessionAffinityConfig: {}
    type: ClusterIP
    externalPort: 8080
    nodePort:
      http:
  executor: CeleryExecutor
  image:
    repository: apache/airflow
    tag: 2.1.3-python3.7
    pullPolicy: Always
  schedulerNumRuns: "-1"
  schedulerDoPickle: true
  webReplicas: 1
  config:
    AIRFLOW_HOME: /opt/airflow
    AIRFLOW__CORE__PARALLELISM: "32"
    AIRFLOW__CORE__DAG_CONCURRENCY: "32"
    AIRFLOW__CORE__NON_POOLED_TASK_SLOT_COUNT: "32"
    AIRFLOW__CELERY__WORKER_AUTOSCALE: "8,6"
    AIRFLOW__SCHEDULER__PARSING_PROCESSES: "2"
    AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX: "true"
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    AIRFLOW__SCHEDULER__RUN_DURATION: "900"
    AIRFLOW__METRICS__STATSD_ON: "True"
    AIRFLOW__METRICS__STATSD_HOST: "telegraf"
    AIRFLOW__METRICS__STATSD_PORT: "8125"
    AIRFLOW__METRICS__STATSD_PREFIX: "airflow"
    AUTH_AZURE_BASE_URL: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0,
    AUTH_AZURE_ACCESS_TOKEN_URL: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0/token
    AUTH_AZURE_AUTHORIZE_URL: https://login.microsoftonline.com/${tenant-id}/oauth2/v2.0/authorize
    AUTH_AZURE_CLIENT_ID: ${airflow2-web-sp-id}
    AUTH_AZURE_CLIENT_SECRET: ${airflow2-web-sp}
    AUTH_USER_REGISTRATION_ROLE: "User"
    AUTH_USER_REGISTRATION: "true"
  podDisruptionBudgetEnabled: true
  podDisruptionBudget:
    maxUnavailable: 1
  extraVolumeMounts: []
  extraVolumes:
    # Additional volumes for the Scheduler, Worker and Web pods.
    - name: azure-pgbouncer-config
      secret:
        secretName: azure-pgbouncer-config
  extraContainers:
    - name: azure-pgbouncer-sidecar
      image: mcr.microsoft.com/azure-oss-db-tools/pgbouncer-sidecar:latest
      # Uncomment below if you always want the latest version
      # imagePullPolicy: Always
      ports:
        - containerPort: 5432
      volumeMounts:
        - name: azure-pgbouncer-config
          mountPath: '/etc/pgbouncer'
          # writes update the secret, we do not want to do this
          readOnly: true
      livenessProbe:
        tcpSocket:
          # This must match the port your applications use to talk to postgres
          port: 5432
        periodSeconds: 60
      lifecycle:
        preStop:
          exec:
            command: ['/bin/sh', '-c', 'killall -INT pgbouncer && sleep 120']
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ['all']
  dbMigrations:
    enabled: false

scheduler:
  resources:
    limits:
      cpu: "1.5"
      memory: "2G"
    requests:
      cpu: "1"
      memory: "1G"
  extraPipPackages:
    - "apache-airflow[databricks,azure]==2.1.3"
flower:
  enabled: false

web:
  extraPipPackages:
    - "Authlib~=0.15.4"
    - "Flask-AppBuilder~=3.3.4"
  webserverConfig:
    existingSecret: "airflow-webserver-config"
  baseUrl: "https://${airflow2-web-dns-name}.westeurope.cloudapp.azure.com"
  resources: {}
  labels: {}
  podLabels: {}
  annotations: {}
  podAnnotations: {}
  initialStartupDelay: 60
  initialDelaySeconds: 360
  minReadySeconds: 120
  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5
  nodeSelector: {}
  affinity: {}
  tolerations: []
  secretsDir: /opt/airflow/secrets
  secrets: []
workers:
  extraPipPackages:
    - "apache-airflow[databricks,azure]==2.1.3"
  enabled: true
  replicas: ${number-of-workers}
  autoscaling:
    enabled: true
    maxReplicas: 10
    metrics:
      - type: Resource
        resource:
          name: memory
          target:
            type: Utilization
            averageUtilization: 80
  terminationPeriod: 30
  resources:
    limits:
      cpu: "2"
      memory: "4G"
    requests:
      cpu: "1.5"
      memory: "2.5G"
  celery:
    instances: 16
    gracefullTermination: true
    gracefullTerminationPeriod: 600
  secretsDir: /opt/airflow/secrets

ingress:
  enabled: false
dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc
  path: /opt/airflow/dags
logs:
  persistence:
    enabled: true
    existingClaim: airflow-logs-pvc
  path: /opt/airflow/logs
rbac:
  create: true
serviceAccount:
  create: true
  name:
  annotations: {}
postgresql:
  enabled: false
redis:
  enabled: false
serviceMonitor:
  enabled: false
prometheusRule:
  enabled: false

pgbouncer:
  enabled: false
externalDatabase:
  type: postgres
  host: 127.0.0.1
  port: 5432
  database: airflow
  user: ${airflow2-postgre-login}@${airflow2-postgre-name}
  passwordSecret: "airflow-postgres-redis"
  passwordSecretKey: "postgresql-password"
  properties: ""
externalRedis:
  host: ${airflow2-redis-name}.redis.cache.windows.net
  port: 6379
  databaseNumber: 1
  passwordSecret: "airflow-postgres-redis"
  passwordSecretKey: "redis-password"
  properties: ""

telegraf:
  enabled: false

```

</details>

## issues/bug
The "check-db" init-container will check DB, and it does not work, if we set the pgbouncer as a side-car (like described here: https://hub.docker.com/_/microsoft-azure-oss-db-tools-pgbouncer-sidecar?tab=description), see above ```extraContainers``` section.
Reason: 
- the init-container will try to connect to the DB, which is pointed as 127.0.0.1, but the side-car container has not been started yet
- the side-car container waits for the init container, the init-container waits for the db connection to come up.

#### detail of the pod log
<details>
<summary>click to expand</summary>

```
kubectl logs -n airflow airflow-worker-3 -c airflow-worker
Error from server (BadRequest): container "airflow-worker" in pod "airflow-worker-3" is waiting to start: PodInitializing
kubectl logs -n airflow airflow-worker-3 -c check-db
[2021-11-14 20:44:17,585] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) could not connect to server: Connection refused
  Is the server running on host "127.0.0.1" and accepting
  TCP/IP connections on port 5432?

(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
  Is the server running on host "127.0.0.1" and accepting
  TCP/IP connections on port 5432?

```

</details>

## suggestion:
allow "check-db" to be started later or disabled by chart user.

**Comment by thesuperzapper** [comment]
@minnieshi the chart supports PgBouncer by default [see the `pgbouncer.*` values](https://github.com/airflow-helm/charts/blob/e1d49498426add959350ab8efacead8f96400759/charts/airflow/values.yaml#L1353-L1368).

I imagine you are trying to use a non-default method because of https://github.com/airflow-helm/charts/issues/412, hopefully, we will resolve that very soon. (It's a trivial fix, but does require a new value, so must be in the next minor release `8.6.0`, and there are a bunch of other things we need to get `8.6.0` ready for Airflow 2.2)

**Comment by minnieshi** [comment]
You imagined correctly, could not use the default pgbouncer with azure postgresql single server. Had to use my own pgbouncer in the end, and pointed the externaldB to the pgbouncer service. 

I wanted to contribute to the mentioned issue, but I am new in chart development, or testing it, would be nice if the repo has some guidance how to contribute (prerequisite knowledge and links).

You can close this if there is no need to fix the stated issue/suggestion.
