### ISSUE TITLE
Scheduler, Db-migrations, Flower, and Web pods all hang at same "Started container check-db" task

### ISSUE THREAD

**Issue by lemmikens** [airflow-helm/charts#492]
Hi there! My Airflow deploy on EKS Fargate keeps hanging on the same "Started container check-db" task. Below are the logs from flower (the rest look very similar)

```
$ kubectl describe pod airflow-flower-57cbf69f5f-jnzd6 -n airflow
Name:                 airflow-flower-57cbf69f5f-jnzd6
Namespace:            airflow
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 fargate-ip-10-6-10-86.ec2.internal/10.6.10.86
Start Time:           Wed, 05 Jan 2022 14:11:18 -0600
Labels:               app=airflow
                      component=flower
                      eks.amazonaws.com/fargate-profile=fp-airflow
                      pod-template-hash=57cbf69f5f
                      release=airflow
Annotations:          CapacityProvisioned: 0.25vCPU 0.5GB
                      Logging: LoggingDisabled: LOGGING_CONFIGMAP_NOT_FOUND
                      checksum/secret-config-envs: 119f8e6f87fdafe4bfd88cd84e36299ef896da39dcc3e4d8b11827dc920866d3
                      checksum/secret-local-settings: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
                      cluster-autoscaler.kubernetes.io/safe-to-evict: true
                      kubernetes.io/psp: eks.privileged
Status:               Pending
IP:                   10.6.10.86
IPs:
  IP:           10.6.10.86
Controlled By:  ReplicaSet/airflow-flower-57cbf69f5f
Init Containers:
  check-db:
    Container ID:  containerd://64a2f94f01ec8e746b4ee77e023edb46a0b90ed02169964b5959982df7344c09
    Image:         apache/airflow:2.0.1-python3.8
    Image ID:      docker.io/apache/airflow@sha256:c416fffb47b395b0a87881096b05998edd0b7fbc127a7184e649cf23c132a7db
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
      /entrypoint
    Args:
      bash
      -c
      exec timeout 60s airflow db check
    State:          Running
      Started:      Wed, 05 Jan 2022 14:13:23 -0600
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      airflow-config-envs  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:
      REDIS_PASSWORD:
      CONNECTION_CHECK_MAX_COUNT:  0
      AIRFLOW_WORKING_DIRECTORY:   <working_efs_path>
    Mounts:
      /opt/efs/ from airflow-efs-dag (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7zq6r (ro)
  wait-for-db-migrations:
    Container ID:
    Image:         apache/airflow:2.0.1-python3.8
    Image ID:
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/dumb-init
      --
      /entrypoint
    Args:
      bash
      -c
      exec airflow db check-migrations -t 60
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment Variables from:
      airflow-config-envs  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:
      REDIS_PASSWORD:
      CONNECTION_CHECK_MAX_COUNT:  0
      AIRFLOW_WORKING_DIRECTORY:   <working_efs_path>
    Mounts:
      /opt/efs/ from airflow-efs-dag (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7zq6r (ro)
Containers:
  airflow-flower:
    Container ID:
    Image:         apache/airflow:2.0.1-python3.8
    Image ID:
    Port:          5555/TCP
    Host Port:     0/TCP
    Command:
      /usr/bin/dumb-init
      --
      /entrypoint
    Args:
      bash
      -c
      exec airflow celery flower
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       exec [bash -c exec curl 'http://localhost:5555'] delay=10s timeout=5s period=10s #success=1 #failure=6
    Readiness:      exec [bash -c exec curl 'http://localhost:5555'] delay=10s timeout=5s period=10s #success=1 #failure=6
    Environment Variables from:
      airflow-config-envs  Secret  Optional: false
    Environment:
      DATABASE_PASSWORD:
      REDIS_PASSWORD:
      CONNECTION_CHECK_MAX_COUNT:  0
      AIRFLOW_WORKING_DIRECTORY:   <working_efs_path>
    Mounts:
      /opt/efs/ from airflow-efs-dag (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7zq6r (ro)
Conditions:
  Type              Status
  Initialized       False
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  airflow-efs-dag:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  airflow
    ReadOnly:   false
  kube-api-access-7zq6r:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason           Age   From               Message
  ----     ------           ----  ----               -------
  Warning  LoggingDisabled  29m   fargate-scheduler  Disabled logging because aws-logging configmap was not found. configmap "aws-logging" not found
  Normal   Scheduled        28m   fargate-scheduler  Successfully assigned airflow/airflow-flower-57cbf69f5f-jnzd6 to fargate-ip-10-6-10-86.ec2.internal
  Normal   Pulling          28m   kubelet            Pulling image "apache/airflow:2.0.1-python3.8"
  Normal   Pulled           26m   kubelet            Successfully pulled image "apache/airflow:2.0.1-python3.8" in 1m57.885221986s
  Normal   Created          26m   kubelet            Created container check-db
  Normal   Started          26m   kubelet            Started container check-db
```

And here is the values.yaml

```
## enable this value if you pass `--wait` to your `helm install`
##
helmWait: false

###################################
# Airflow - Common Configs
###################################
airflow:
  ## if we use legacy 1.10 airflow commands
  ##
  legacyCommands: false

  ## configs for the airflow container image
  ##
  image:
    repository: apache/airflow
    tag: 2.0.1-python3.8
    ## values: Always or IfNotPresent
    pullPolicy: IfNotPresent
    pullSecret: ""
    uid: 50000
    gid: 50000


  executor: CeleryExecutor


  fernetKey: "7T512UXSSmBOkpWimFHIVb8jK6lfmSAvx4mO6Arehnc="

  ##
  config:

        # S3 Logging
        AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
        AIRFLOW__LOGGING__REMOTE_LOGGING : "True"
        AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID : "s3_conn"
        AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER : "s3://<s3-path>/"
        AIRFLOW__CORE__ENCRYPT_S3_LOGS: "False"
        AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOGGING: "True"
        AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_BASE_LOG_FOLDER: "s3://<s3-path>/"
        AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__REMOTE_LOG_CONN_ID: "s3_conn"
        AIRFLOW__KUBERNETES_ENVIRONMENT_VARIABLES__AIRFLOW__CORE__ENCRYPT_S3_LOGS: "False"
        
        
        
        

  ## a list of initial users to create
  ##
  users:
    - username: admin
      password: admin
      role: Admin
      email: admin@example.com
      firstName: admin
      lastName: admin


  usersUpdate: true

  ##
  connections: 
    - id: s3_conn
      type: aws
      description: my AWS connection
      extra: |-
        { "aws_access_key_id": "<aws_key_id>",
          "aws_secret_access_key": "<aws_key>",
          "region_name":"<aws-region>" 
        }

  connectionsUpdate: true


  variables: []


  variablesUpdate: true

  pools: []


  poolsUpdate: true


  podAnnotations: {}


  # extraPipPackages:
  #   # - "-c"
  #   # - "https://raw.githubusercontent.com/apache/airflow/constraints-2.0.1/constraints-3.8.txt"
  #   - "apache-airflow-providers-amazon"
  #   - "awscli"
    # - "apache-airflow[aws]==2.0.1"
  # - "six python-dateutil boto3 botocore s3transfer jmespath urllib3 "
  # - "watchtower"
    

  extraEnv: 
    - name: AIRFLOW_WORKING_DIRECTORY
      value: <working_efs_path>

  extraContainers: []

  extraVolumeMounts: 
    - name: airflow-efs-dag
      mountPath: /opt/efs/
    

  extraVolumes:
    - name: airflow-efs-dag
      persistentVolumeClaim:
        claimName: airflow
    

  kubernetesPodTemplate:

    stringOverride: ""


    nodeSelector: {}


    affinity: {}


    tolerations: []

 
    podAnnotations: {}


    securityContext: {}


    extraPipPackages: []


    extraVolumeMounts: []

    extraVolumes: []

###################################
# Airflow - Scheduler Configs
###################################
scheduler:

  replicas: 1


  resources: {}

  nodeSelector: {}


  affinity: {}

  tolerations: []


  securityContext: {}

  labels: {}

  podLabels: {}

  annotations: {}

  podAnnotations: {}

  safeToEvict: true


  podDisruptionBudget:

    enabled: false


    maxUnavailable: ""

    minAvailable: ""

 
  numRuns: -1


  livenessProbe:
    enabled: false
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 10
    failureThreshold: 5


  extraPipPackages: []


  extraVolumeMounts: []


  extraVolumes: []

  extraInitContainers: []

###################################
# Airflow - WebUI Configs
###################################
web:

  webserverConfig:

    stringOverride: ""

 
    existingSecret: ""


  replicas: 1

  resources: {}

  nodeSelector: {}

  affinity: {}

  tolerations: []

  securityContext: {}

  labels: {}

  podLabels: {}

  annotations: {}

  podAnnotations: {}

  safeToEvict: true

  podDisruptionBudget:

    enabled: false

    maxUnavailable: ""

    minAvailable: ""

  service:
    type: NodePort

  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6


  extraPipPackages: []

  extraVolumeMounts: []


  extraVolumes: []

###################################
# Airflow - Celery Worker Configs
###################################
workers:

  enabled: true

  replicas: 1

  resources: {}

  nodeSelector: {}

  affinity: {}

  tolerations: []


  securityContext: {}

  labels: {}


  podLabels: {}

  annotations: {}

  podAnnotations: {}

  safeToEvict: true

  podDisruptionBudget:

    enabled: false


    maxUnavailable: ""


    minAvailable: ""


  
  autoscaling:
    enabled: false
    maxReplicas: 2
    metrics: []


  celery:

    gracefullTermination: false


    gracefullTerminationPeriod: 600


  terminationPeriod: 60


  extraPipPackages: []

  extraVolumeMounts: []

  extraVolumes: []

###################################
# Airflow - Flower Configs
###################################
flower:

  enabled: true


  replicas: 1


  resources: {}

  nodeSelector: {}

  affinity: {}

  tolerations: []

  securityContext: {}


  labels: {}


  podLabels: {}


  annotations: {}


  podAnnotations: {}


  safeToEvict: true


  podDisruptionBudget:
 
    enabled: false

    maxUnavailable: ""

    minAvailable: ""


  oauthDomains: ""


  basicAuthSecret: ""


  basicAuthSecretKey: ""


  service:
    annotations: {}
    type: ClusterIP
    externalPort: 5555
    loadBalancerIP: ""
    loadBalancerSourceRanges: []
    nodePort:
      http:


  readinessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6

 
  livenessProbe:
    enabled: true
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 6


  extraPipPackages: []

  extraVolumeMounts: []

  extraVolumes: []

###################################
# Airflow - Logs Configs
###################################
logs:

  path: /opt/airflow/logs


  persistence:

    enabled: true

    existingClaim: ""

    subPath: ""

    storageClass: ""

    accessMode: ReadWriteMany

    size: 1Gi

###################################
# Airflow - DAGs Configs
###################################
dags:

  path: <working_efs_path>/dags/

  persistence:

    enabled: false

    existingClaim: ""

    subPath: "/airflow/dags"

    storageClass: "efs-sc"

    accessMode: ReadWriteMany

    size: 5Gi


  gitSync:

    enabled: false

    ## the git-sync container image
    ##
    image:
      repository: k8s.gcr.io/git-sync/git-sync
      tag: v3.2.2
      ## values: Always or IfNotPresent
      pullPolicy: IfNotPresent
      uid: 65533
      gid: 65533


    resources: {}


    repo: ""


    repoSubPath: ""

    ## the git branch to check out
    ##
    branch: master

    ## the git revision (tag or hash) to check out
    ##
    revision: HEAD

    ## shallow clone with a history truncated to the specified number of commits
    ##
    depth: 1

    ## the number of seconds between syncs
    ##
    syncWait: 60

    ## the max number of seconds allowed for a complete sync
    ##
    syncTimeout: 120

    ## the name of a pre-created Secret with git http credentials
    ##
    httpSecret: ""

    ## the key in `dags.gitSync.httpSecret` with your git username
    ##
    httpSecretUsernameKey: username

    ## the key in `dags.gitSync.httpSecret` with your git password/token
    ##
    httpSecretPasswordKey: password

    ## the name of a pre-created Secret with git ssh credentials
    ##
    sshSecret: ""

    ## the key in `dags.gitSync.sshSecret` with your ssh-key file
    ##
    sshSecretKey: id_rsa

    ## the string value of a "known_hosts" file (for SSH only)
    ##
    ## WARNING:
    ## - known_hosts verification will be disabled if left empty, making you more
    ##   vulnerable to repo spoofing attacks
    ##
    ## EXAMPLE:
    ##    sshKnownHosts: |-
    ##      <HOST_NAME> ssh-rsa <HOST_KEY>
    ##
    sshKnownHosts: ""

###################################
# Kubernetes - Ingress Configs
###################################
ingress:
  ## if we should deploy Ingress resources
  ##
  enabled: true

  ## configs for the Ingress of the web Service
  ##
  web:
    ## annotations for the web Ingress
    ##
    annotations: {}

    ## additional labels for the web Ingress
    ##
    labels: {}

    ## the path for the web Ingress
    ##
    ## WARNING:
    ## - do NOT include the trailing slash (for root, set an empty string)
    ##
    ## EXAMPLE: (if set to "/airflow")
    ## - UI:     http://example.com/airflow/admin
    ## - API:    http://example.com/airflow/api
    ## - HEALTH: http://example.com/airflow/health
    ##
    path: ""

    ## the hostname for the web Ingress
    ##
    host: ""

    ## configs for web Ingress TLS
    ##
    tls:
      ## enable TLS termination for the web Ingress
      ##
      enabled: false

      ## the name of a pre-created Secret containing a TLS private key and certificate
      ##
      secretName: ""

    ## http paths to add to the web Ingress before the default path
    ##
    ## EXAMPLE:
    ##   precedingPaths:
    ##     - path: "/*"
    ##       serviceName: "my-service"
    ##       servicePort: "port-name"
    ##
    precedingPaths: []

    ## http paths to add to the web Ingress after the default path
    ##
    ## EXAMPLE:
    ##   succeedingPaths:
    ##     - path: "/extra-service"
    ##       serviceName: "my-service"
    ##       servicePort: "port-name"
    ##
    succeedingPaths: []

  ## configs for the Ingress of the flower Service
  ##
  flower:
    ## annotations for the flower Ingress
    ##
    annotations: {}

    ## additional labels for the flower Ingress
    ##
    labels: {}

    ## the path for the flower Ingress
    ##
    ## WARNING:
    ## - do NOT include the trailing slash (for root, set an empty string)
    ##
    ## EXAMPLE: (if set to "/airflow/flower")
    ## - UI: http://example.com/airflow/flower
    ##
    path: ""

    ## the hostname for the flower Ingress
    ##
    host: ""

    ## configs for flower Ingress TLS
    ##
    tls:
      ## enable TLS termination for the flower Ingress
      ##
      enabled: false

      ## the name of a pre-created Secret containing a TLS private key and certificate
      ##
      secretName: ""

    ## http paths to add to the flower Ingress before the default path
    ##
    ## EXAMPLE:
    ##   precedingPaths:
    ##     - path: "/*"
    ##       serviceName: "my-service"
    ##       servicePort: "port-name"
    ##
    precedingPaths: []

    ## http paths to add to the flower Ingress after the default path
    ##
    ## EXAMPLE:
    ##   succeedingPaths:
    ##     - path: "/extra-service"
    ##       serviceName: "my-service"
    ##       servicePort: "port-name"
    ##
    succeedingPaths: []

###################################
# Kubernetes - RBAC
###################################
rbac:
  ## if Kubernetes RBAC resources are created
  ##
  ## NOTE:
  ## - these allow the service account to create/delete Pods in the airflow namespace,
  ##   which is required for the KubernetesPodOperator() to function
  ##
  create: true

  ## if the created RBAC Role has GET/LIST on Event resources
  ##
  ## NOTE:
  ## - this is needed for KubernetesPodOperator() to use `log_events_on_failure=True`
  ##
  events: true

###################################
# Kubernetes - Service Account
###################################
serviceAccount:
  ## if a Kubernetes ServiceAccount is created
  ##
  ## NOTE:
  ## - if false, you must create the service account outside of this chart,
  ##   with the name: `serviceAccount.name`
  ##
  create: true

  ## the name of the ServiceAccount
  ##
  ## NOTE:
  ## - by default the name is generated using the `airflow.serviceAccountName` template in `_helpers/common.tpl`
  ##
  name: ""

  ## annotations for the ServiceAccount
  ##
  ## EXAMPLE: (to use WorkloadIdentity in Google Cloud)
  ##   annotations:
  ##     iam.gke.io/gcp-service-account: <<GCP_SERVICE>>@<<GCP_PROJECT>>.iam.gserviceaccount.com
  ##
  annotations: {}

###################################
# Kubernetes - Extra Manifests
###################################
## extra Kubernetes manifests to include alongside this chart
##
## NOTE:
## - this can be used to include ANY Kubernetes YAML resource
##
## EXAMPLE:
##   extraManifests:
##    - apiVersion: cloud.google.com/v1beta1
##      kind: BackendConfig
##      metadata:
##        name: "{{ .Release.Name }}-test"
##      spec:
##        securityPolicy:
##          name: "gcp-cloud-armor-policy-test"
##
extraManifests: []

###################################
# Database - PostgreSQL Chart
# - https://github.com/helm/charts/tree/master/stable/postgresql
###################################
postgresql:

  enabled: false

  postgresqlDatabase: airflow


  postgresqlUsername: postgres


  postgresqlPassword: airflow


  persistence:

    enabled: false

    storageClass: ""

    accessModes:
      - ReadWriteOnce

    size: 8Gi

  master:

    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

###################################
# Database - External Database
# - these configs are only used when `postgresql.enabled` is false
###################################
externalDatabase:

  type: postgres

  host: REDACTED


  port: 5432

  database: airflow
  postgresqlPassword: REDACTED

  user: postgres


###################################
# Database - Redis Chart
# - https://github.com/helm/charts/tree/master/stable/redis
###################################
redis:

  enabled: true

  password: airflow

  existingSecret: ""

  existingSecretPasswordKey: "redis-password"

  cluster:

    enabled: false

    slaveCount: 1


  master:

    resources: {}

    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

    persistence:

      enabled: false

      storageClass: ""

      accessModes:
      - ReadWriteOnce

      size: 8Gi


  slave:

    resources: {}

    podAnnotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "true"

    persistence:

      enabled: false

      storageClass: ""

      accessModes:
        - ReadWriteOnce

      size: 8Gi

###################################
# Database - External Database
# - these configs are only used when `redis.enabled` is false
###################################
externalRedis:

  host: localhost

  port: 6379

  databaseNumber: 1

  passwordSecret: ""

  passwordSecretKey: "redis-password"

###################################
# Prometheus Operator - ServiceMonitor
###################################
serviceMonitor:

  enabled: false

  selector:
    prometheus: kube-prometheus

  path: /admin/metrics

  interval: "30s"

###################################
# Prometheus Operator - PrometheusRule
###################################
prometheusRule:

  enabled: false

  additionalLabels: {}

  groups: []

```
Please let me know if you need anything else in order to troubleshoot and thanks in advance for the assistance!!

**Comment by thesuperzapper** [comment]
@lemmikens what version of the chart are you using?

Also, can you confirm that all the pods created by the chart are in a healthy `Running` state?

If not, can you provide the logs for any `CrashLoopBackoff` ones?

**Comment by lemmikens** [comment]
1. Latest (8.5.2). 
2. The only pods that are healthy and running are Redis and Postgres. 
3. The logs for CrashLoopBackoff from Flower is the one I posted up top. 

Thanks for the response and please let me know if you need any other info!

**Comment by thesuperzapper** [comment]
@lemmikens you posted a `kubectl describe` can you post the actual container logs from `kubectl logs`?

Also, which container within the Pod is failing (make sure to provide the logs from that one)?

**Comment by lemmikens** [comment]
logs from the check-db container on the web pod: 

```[2022-01-14 16:53:29,774] {cli_action_loggers.py:105} WARNING - Failed to log action with (psycopg2.OperationalError) ERROR:  pgbouncer cannot connect to server
ERROR:  pgbouncer cannot connect to server

(Background on this error at: http://sqlalche.me/e/13/e3q8)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: ERROR:  pgbouncer cannot connect to server
ERROR:  pgbouncer cannot connect to server


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/db_command.py", line 96, in check
    db.check()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/db.py", line 782, in check
    session.execute('select 1 as is_alive;')
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1295, in execute
    return self._connection_for_bind(bind, close_with_result=True).execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1150, in _connection_for_bind
    return self.transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 433, in _connection_for_bind
    conn = bind._contextual_connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2339, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1583, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 508, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) ERROR:  pgbouncer cannot connect to server
ERROR:  pgbouncer cannot connect to server

(Background on this error at: http://sqlalche.me/e/13/e3q8)```

**Comment by emilianomoscato** [comment]
Hello everybody,

We're running chart 8.5.3 and when enable Pbouncer with the default configuration Airflow doesn't start and we get: 
```
ERROR:  pgbouncer cannot connect to server
```
at check-db and Pgbouncer pods.

Disabling Pgbouncer makes everything works OK.

I'm trying to figure out why Pgbouncer is not connecting. We are using Postgres 12.7 instance at a AWS RDS.

**Comment by lemmikens** [comment]
Thank you @emilianomoscato, That fixed my issue! Now I'm having another issue regarding webserver timeouts, but I will open up another issue regarding that one if I can't work through it. Much appreciated!

**Comment by thesuperzapper** [comment]
@emilianomoscatoare you still having the issue with pgbouncer, if so, do you mind raising a new issue so that we can fix it?
