### ISSUE TITLE
Worker POD error WorkerLostError('Worker exited prematurely: signal 15 (SIGTERM).',)

### ISSUE THREAD

**Issue by adib-next** [airflow-helm/charts#50]
Has anyone come across this issue where the worker crashes with this error ?

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/worker/worker.py", line 208, in start
    self.blueprint.start(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/bootsteps.py", line 369, in start
    return self.obj.start()
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/worker/consumer/consumer.py", line 599, in start
    c.loop(*c.loop_args())
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/worker/loops.py", line 83, in asynloop
    next(loop)
  File "/home/airflow/.local/lib/python3.6/site-packages/kombu/asynchronous/hub.py", line 308, in create_loop
    events = poll(poll_timeout)
  File "/home/airflow/.local/lib/python3.6/site-packages/kombu/utils/eventio.py", line 84, in poll
    return self._epoll.poll(timeout if timeout is not None else -1)
  File "/home/airflow/.local/lib/python3.6/site-packages/celery/apps/worker.py", line 285, in _handle_request
    raise exc(exitcode)
celery.exceptions.WorkerShutdown: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/billiard/pool.py", line 1267, in mark_as_worker_lost
    human_status(exitcode)),
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 15 (SIGTERM).

**Comment by mdcsaenz** [comment]
I have the same issue, anyone else?

**Comment by renanleme** [comment]
I have this issue also and I couldn't find the reason, yet!

**Comment by renanleme** [comment]
@adib-next @mdcsaenz Did you guys updated the Airflow image version without updating the helm chart? 🤔

**Comment by thesuperzapper** [comment]
@mdcsaenz @renanleme can you please check if you still have this issue after version `8.0.1` of the chart?

**Comment by david30907d** [comment]
bumped into this issue also, did anyone find the solution?

**Comment by david30907d** [comment]
> @mdcsaenz @renanleme can you please check if you still have this issue after version `8.0.1` of the chart?

will try version `8.0.1` thanks~

**Comment by thesuperzapper** [comment]
@david30907d are you still getting these issues (check with `8.0.5` preferably)

**Comment by renanleme** [comment]
I think I fixed my issue, at least for now.
My workers were using `standard` disk instead of `ssd's` and the IOP's were too high so the pod was being killed.
After changing the disks of the cluster to SSD's the issue is gone. At least for now...
Thanks for your help!

**Comment by david30907d** [comment]
> @david30907d are you still getting these issues (check with `8.0.5` preferably)

Hi @thesuperzapper I'm using `7.16.0` and it turns out my `AIRFLOW__CELERY__WORKER_CONCURRENCY` is too high.

decrease it and everything works fine~ tks
