### ISSUE TITLE
`airflow.fernetKey` and `airflow.webserverSecretKey` overshadow `_CMD` configs

### ISSUE THREAD

**Issue by aodj** [airflow-helm/charts#506]
### Checks

- [X] I have checked for [existing issues](https://github.com/airflow-helm/charts/issues).

### Description

I've been working on setting up an init container that creates a Fernet key and a webserver secret key when the chart is installed, and am reading them using the `AIRFLOW__CORE__FERNET_KEY_CMD` and `AIRFLOW__WEBSERVER__SECRET_KEY_CMD` environment options. 

Due to the `fernetKey` and `webserverSecretKey` options having more "power" due to their explicit handling, it doesn't seem to be able to unset the default value; if I set it to an empty string, I end up with two env-vars in my pods, with Airflow apparently taking the empty string as the default:

```bash
$ env | sort | grep -i fernet
AIRFLOW__CORE__FERNET_KEY=
AIRFLOW__CORE__FERNET_KEY_CMD=while [ ! -f /opt/airflow/fernet/fernet.key ]; do sleep 1; done; cat /opt/airflow/fernet/fernet.key
$ airflow config get-value core fernet_key

$ # this is an empty string
```

The [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/stable/howto/set-config.html) doesn't appear to mention anything about an order of precedence when using more than one of these options, and it doesn't appear possible to unset the env-vars that are set by the chart. _Edit: found the listing on that same page 🤦_

For reference, the usage of the _CMD is at least mentioned in a few tickets on this repo, f.ex #333 so some people know about it, but perhaps it's not widely used as a feature.

### Are you willing & able to help?

- [x] I am able to submit a PR!
- [X] I can provide feedback!

**Comment by aodj** [comment]
As additional information, if the fernet key is an empty string, the `sync-airflow-connections` pod dies with the following exception, which in turn cascades into Airflow itself since the connections my dags are relying upon don't appear.

```
[2022-01-19 14:38:23,247] {sync_connections.py:364} INFO - BEGIN: airflow connections sync
[2022-01-19 14:38:23,273] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
Traceback (most recent call last):
  File "/mnt/scripts/sync_connections.py", line 380, in <module>
    main(sync_forever=True)
  File "/mnt/scripts/sync_connections.py", line 99, in main
    sync_with_airflow()
  File "/mnt/scripts/sync_connections.py", line 374, in sync_with_airflow
    sync_all_connections(connection_wrappers=VAR__CONNECTION_WRAPPERS)
  File "/mnt/scripts/sync_connections.py", line 366, in sync_all_connections
    sync_connection(connection_wrapper)
  File "/mnt/scripts/sync_connections.py", line 340, in sync_connection
    if compare_connections(c_new, c_old):
  File "/mnt/scripts/sync_connections.py", line 319, in compare_connections
    and c1.extra == c2.extra
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/attributes.py", line 365, in __get__
    retval = self.descriptor.__get__(instance, owner)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/connection.py", line 259, in get_extra
    raise AirflowException(
airflow.exceptions.AirflowException: Can't decrypt `extra` params for login=None,                    FERNET_KEY configuration is missing
```
