### ISSUE TITLE
Task run faield on Kubernetes Executor after update to airflow 2.0

### ISSUE THREAD

**Issue by nguyenkien1402** [airflow-helm/charts#56]
I was trying to upgrade airflow 1.10.12 to airflow 2.0.0 and I have encountered a lot of issues.
After taking a recommendation from @dr1992 and @Swalloow. I was able to get airflow 2.0.0 up and running.

Now come to another issue when I trigger the example dag: **example_kubeenetes_executor_config**. 
I check the log and here is what I get

```
[2021-01-12 04:03:53,149] {cli_action_loggers.py:105} WARNING - Failed to log action with (sqlite3.OperationalError) no such table: log
[SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (?, ?, ?, ?, ?, ?, ?)]
[parameters: ('2021-01-12 04:03:53.145763', 'from_just_another_git_dag_kubernetes_executor', 'from_just_another_git_my_start_task', 'cli_task_run', '2021-01-12 04:03:39.626322', 'airflow', '{"host_name": "fromjustanothergitdagkubernetesexecutorfromjustanothergitmystar", "full_command": "[\'/home/airflow/.local/bin/airflow\', \'tasks\', \ ... (94 characters truncated) ... sk\', \'2021-01-12T04:03:39.626322+00:00\', \'--local\', \'--pool\', \'default_pool\', \'--subdir\', \'/opt/airflow/dags/just_another_git_dag.py\']"}')]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
[2021-01-12 04:03:53,150] {dagbag.py:440} INFO - Filling up the DagBag from /opt/airflow/dags/just_another_git_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: task_instance

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/__main__.py", line 40, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/cli.py", line 89, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/cli/commands/task_command.py", line 223, in task_run
    ti.refresh_from_db()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 556, in refresh_from_db
    ti = qry.first()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3429, in first
    ret = list(self[0:1])
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3203, in __getitem__
    return list(res)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: task_instance
[SQL: SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.pool_slots AS task_instance_pool_slots, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance.queued_by_job_id AS task_instance_queued_by_job_id, task_instance.pid AS task_instance_pid, task_instance.executor_config AS task_instance_executor_config, task_instance.external_executor_id AS task_instance_external_executor_id
FROM task_instance
WHERE task_instance.dag_id = ? AND task_instance.task_id = ? AND task_instance.execution_date = ?
 LIMIT ? OFFSET ?]
[parameters: ('from_just_another_git_dag_kubernetes_executor', 'from_just_another_git_my_start_task', '2021-01-12 04:03:39.626322', 1, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
```

I check the DB and I confirm the **log** table and **task_instance** table are there.

So what causes this error? 
I know we are trying to support both airflow 1 and airflow 2 but is there anything I need to concern or modify when coming to upgrade airflow 2.0?

**Comment by assofour** [comment]
I have same issue as I used docker-compose to run airflow 2.0 stack.

`cia_airflow_webserver_1 | [2021-02-06 17:11:19,506] {db.py:678} INFO - Creating tables
cia_airflow_webserver_1 | INFO  [alembic.runtime.migration] Context impl MySQLImpl.
cia_airflow_webserver_1 | INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
cia_airflow_scheduler_1 | [2021-02-06 17:11:20,824] {cli_action_loggers.py:105} WARNING - Failed to log action with (_mysql_exceptions.ProgrammingError) (1146, "Table 'airflowdb.log' doesn't exist")
cia_airflow_scheduler_1 | [SQL: INSERT INTO log (dttm, dag_id, task_id, event, execution_date, owner, extra) VALUES (%s, %s, %s, %s, %s, %s, %s)]
cia_airflow_scheduler_1 | [parameters: (datetime.datetime(2021, 2, 6, 9, 11, 20, 790055), None, None, 'cli_scheduler', None, 'airflow', '{"host_name": "9aca2dc5d5ab", "full_command": "[\'/home/airflow/.local/bin/airflow\', \'scheduler\']"}')]
cia_airflow_scheduler_1 | (Background on this error at: http://sqlalche.me/e/13/f405)`

**Comment by thesuperzapper** [comment]
Please view https://github.com/airflow-helm/charts/issues/58 for updates on Airflow 2.0

**Comment by IndrajeetTech2020** [comment]
/usr/local/lib/python3.8/dist-packages/airflow/configuration.py:332 DeprecationWarning: The dag_processor_manager_log_location option in [core] has been moved to the dag_processor_manager_log_location option in [logging] - the old setting has been used, but please update your config.
/usr/local/lib/python3.8/dist-packages/airflow/configuration.py:332 DeprecationWarning: The statsd_on option in [scheduler] has been moved to the statsd_on option in [metrics] - the old setting has been used, but please update your config.
/usr/local/lib/python3.8/dist-packages/airflow/configuration.py:332 DeprecationWarning: The dag_processor_manager_log_location option in [core] has been moved to the dag_processor_manager_log_location option in [logging] - the old setting has been used, but please update your config.
/usr/local/lib/python3.8/dist-packages/airflow/configuration.py:332 DeprecationWarning: The statsd_on option in [scheduler] has been moved to the statsd_on option in [metrics] - the old setting has been used, but please update your config.
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-05-18 16:55:08,602] {scheduler_job.py:1247} INFO - Starting the scheduler
[2021-05-18 16:55:08,603] {scheduler_job.py:1252} INFO - Processing each file at most -1 times
[2021-05-18 16:55:08,604] {kubernetes_executor.py:473} INFO - Start Kubernetes executor
[2021-05-18 16:55:08,630] {kubernetes_executor.py:126} INFO - Event: and now my watch begins starting at resource_version: 0
[2021-05-18 16:55:10,550] {scheduler_job.py:1298} ERROR - Exception when executing SchedulerJob._run_scheduler_loop
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.UndefinedColumn: column task_instance.pool_slots does not exist
LINE 1: ...job_id, task_instance.pool AS task_instance_pool, task_insta...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/airflow/jobs/scheduler_job.py", line 1272, in _execute
    self.executor.start()
  File "/usr/local/lib/python3.8/dist-packages/airflow/executors/kubernetes_executor.py", line 482, in start
    self.clear_not_launched_queued_tasks()
  File "/usr/local/lib/python3.8/dist-packages/airflow/utils/session.py", line 65, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/airflow/executors/kubernetes_executor.py", line 443, in clear_not_launched_queued_tasks
    queued_tasks = session.query(TaskInstance).filter(TaskInstance.state == State.QUEUED).all()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column task_instance.pool_slots does not exist
LINE 1: ...job_id, task_instance.pool AS task_instance_pool, task_insta...
                                                             ^

[SQL: SELECT task_instance.try_number AS task_instance_try_number, task_instance.task_id AS task_instance_task_id, task_instance.dag_id AS task_instance_dag_id, task_instance.execution_date AS task_instance_execution_date, task_instance.start_date AS task_instance_start_date, task_instance.end_date AS task_instance_end_date, task_instance.duration AS task_instance_duration, task_instance.state AS task_instance_state, task_instance.max_tries AS task_instance_max_tries, task_instance.hostname AS task_instance_hostname, task_instance.unixname AS task_instance_unixname, task_instance.job_id AS task_instance_job_id, task_instance.pool AS task_instance_pool, task_instance.pool_slots AS task_instance_pool_slots, task_instance.queue AS task_instance_queue, task_instance.priority_weight AS task_instance_priority_weight, task_instance.operator AS task_instance_operator, task_instance.queued_dttm AS task_instance_queued_dttm, task_instance.queued_by_job_id AS task_instance_queued_by_job_id, task_instance.pid AS task_instance_pid, task_instance.executor_config AS task_instance_executor_config, task_instance.external_executor_id AS task_instance_external_executor_id 
FROM task_instance 
WHERE task_instance.state = %(state_1)s]
[parameters: {'state_1': 'queued'}]
(Background on this error at: http://sqlalche.me/e/13/f405)
[2021-05-18 16:55:10,626] {dag_processing.py:451} WARNING - Ending without manager process.
[2021-05-18 16:55:10,626] {scheduler_job.py:1301} INFO - Exited execute loop

**Comment by thesuperzapper** [comment]
@IndrajeetTech2020 can you clarify what your logs are for?

Like what version of the chart, and values you are using?
