### ISSUE TITLE
1.10.15-python3.6: FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by patsevanton** [airflow-helm/charts#90]
Hello! Thanks for helm for airflow.
I try install airflow 1.10.15 by helm

```
helm repo add airflow-stable https://airflow-helm.github.io/charts
helm repo update
helm install --set airflow.image.tag=1.10.15-python3.6,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.sslip.io airflow airflow-stable/airflow --version 7.16.0
```

**What is the bug?**
```
 kubectl logs airflow-web-76596d7bbb-cknjn
*** running webserver...
[2021-03-19 07:28:15,835] {cli_action_loggers.py:107} WARNING - Failed to log action with (psycopg2.OperationalError) FATAL:  password authentication failed for user "postgres"

(Background on this error at: http://sqlalche.me/e/13/e3q8)
  ____________       _____________
 ____    |__( )_________  __/__  /________      __
____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
 _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
[2021-03-19 07:28:16,353] {__init__.py:50} INFO - Using executor CeleryExecutor
[2021-03-19 07:28:16,355] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 495, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 140, in _do_get
    self._dec_overflow()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    with_traceback=exc_tb,
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 656, in __connect
    connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 493, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.6/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "postgres"
```

**What is your Kubernetes Version?**:
```console
$ kubectl version
v1.18.16
```

**What is your Helm version?**:
```console
$ helm version
v3.5.2
```

**Comment by thesuperzapper** [comment]
@patsevanton can you please try with version `8.0.0` of the chart?

**Comment by thesuperzapper** [comment]
@patsevanton any updates?

**Comment by patsevanton** [comment]
May be create new issue?

```
helm repo add airflow-stable https://airflow-helm.github.io/charts
helm repo update
 helm install --set airflow.image.tag=1.10.15-python3.6,ingress.enabled=true,ingress.hosts[0]=airflow.192.168.22.7.sslip.io airflow airflow-stable/airflow --version 8.0.6 
```

Logs
```
kubectl logs  airflow-create-users-7vfjq
[2021-04-12 12:35:18,455] {__init__.py:50} INFO - Using executor CeleryExecutor
[2021-04-12 12:35:18,457] {dagbag.py:417} INFO - Filling up the DagBag from /opt/airflow/dags
Traceback (most recent call last):
  File "/job_scripts/create_users.py", line 6, in <module>
    appbuilder = cached_app().appbuilder
AttributeError: 'DispatcherMiddleware' object has no attribute 'appbuilder'
```

I am switch to chart https://github.com/apache/airflow/tree/master/chart
May be later check

**Comment by thesuperzapper** [comment]
@patsevanton to use this chart with airflow 1.10, you must set `airflow.legacyCommands` to `true`
