### ISSUE TITLE
cannot create directory '/usr/local/airflow/.local': Permission denied

### ISSUE THREAD

**Issue by amtesandip** [airflow-helm/charts#94]
**What is your question?**
When we try to install airflow using helm, pods are going into crashloopbackoff. After checking logs of scheduler we found below error: 
Error: cannot create directory '/usr/local/airflow/.local': Permission denied

We have given -R 777 permission to /usr/local/airflow directory in aws efs and same permission are also given in the code.
Still we are getting Permission denied. 

Kubectl logs attached herewith for more details: -
kubectl logs airflow-scheduler-d66f88c8f-kh74twaiting 10s...
executing initdb
Unable to load the config, contains a configuration error.
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.7/logging/config.py", line 736, in configure_handler
    result = factory(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/airflow/utils/log/file_processor_handler.py", line 50, in __init__
    os.makedirs(self._get_log_directory())
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.7/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/logs'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.7/dist-packages/airflow/__init__.py", line 44, in <module>
    settings.initialize()
  File "/usr/local/lib/python3.7/dist-packages/airflow/settings.py", line 335, in initialize
    LOGGING_CLASS_PATH = configure_logging()
  File "/usr/local/lib/python3.7/dist-packages/airflow/logging_config.py", line 68, in configure_logging
    raise e
  File "/usr/local/lib/python3.7/dist-packages/airflow/logging_config.py", line 63, in configure_logging
    dictConfig(logging_config)
  File "/usr/lib/python3.7/logging/config.py", line 800, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 571, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'processor'

Where do we have to make changes, so that issue can be rectified?

**Comment by thesuperzapper** [comment]
@sandipamte can you please try with version `8.0.0` of the chart?

**Comment by thesuperzapper** [comment]
@sandipamte any updates?

**Comment by sandipamte** [comment]
Still we are getting same error as PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/logs'.
Please let me know any addition information is required form my side.
